{% set name = "jmespath" %}
{% set version = "1.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "a490e280edd1f57d6de88636992d05b71e97d69a26a19f058ecf7d304474bf5e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - jmespath


about:
  home: https://github.com/jmespath/jmespath.py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: JSON Matching Expressions
  dev_url: https://github.com/jmespath/jmespath.py

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
