{% set name = "jmespath" %}
{% set version = "0.9.4" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "bde2aef6f44302dfb30320115b17d030798de8c4110e28d5cf6cf91a7a31074c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - jmespath


about:
  home: https://github.com/jmespath/jmespath.py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'JSON Matching Expressions'
  dev_url: https://github.com/jmespath/jmespath.py
  
extra:
  recipe-maintainers:
    - pmlandwehr
