travis:
  secure:
    BINSTAR_TOKEN: i+7Cr8kBMNYvZLtSXpIB3Z255sCUBsFmHUNWAjOC2nD9fTwnRQqX/LX6NNo0SKDuE8jGOY/hu3qfh75IER2sckOvNAj1jxdGXTO6FZtO9oDoA331UVwqsWbw7/hAA4TWSRemm0boO+fxhqme4bQneK4yPT7bOlKOrVcAyYpNMzKsLlwroZoVe/TIPYTGECYTbpzYh31dGq+j4aY0IxT6DVsn0R5X9LZnzdR541kOAu/fzaNlqiYPmU9sp47wLSrRsSkPN4ycBwly7VHj4b+kfaUK38b4+k+6Smrym4bdjbbbD/5DAPLEQSdUfbYEnRlTd0CXZBd4Uke31T5N1DXRAjk2yTAO452YXABNQaDQHCQCCIsntwO1uLf8OtCfply9EAxIwTiUiHwl3jSM8Vi99qly4Ih3zwom8uwQVQMrnkXevVJRO7ktu2QVi3RS+ssIgPqRlZpGfvLTbXanZSqkRyDQOuEyaOwduZc760z2Aa0M2FXSQoMIDXYm8raJXPmHPD8+nR1+8BgKIJ4raZWqhlMvX0c2fg6NLP6bHk7R1ez1IaDWcp5H+/46qXoRskB2UsV+5LtZ7UcxDNgPDSNma64Cwt5N6Lx3ILC5bWsStkpBLys64Ct7bHd+LXWqtqJMtTouAZwLPPkm+Xe6/QSfpihuZbK1Cwt+NlquF31Smg8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
